import type { Source } from "./types";

/** Default sources for GROVEEMODEL — smaller set for faster first sync. */
export const BUILTIN_SOURCES: Source[] = [
  {
    id: "iptv-org-il",
    name: "IPTV-Org Israel",
    type: "iptv",
    url: "https://iptv-org.github.io/iptv/countries/il.m3u",
    enabled: true,
    autoRefresh: true,
    lastSync: 0,
    channelCount: 0,
    builtin: true,
  },
  {
    id: "iptv-lang-heb",
    name: "IPTV Hebrew",
    type: "iptv",
    url: "https://iptv-org.github.io/iptv/languages/heb.m3u",
    enabled: true,
    autoRefresh: true,
    lastSync: 0,
    channelCount: 0,
    builtin: true,
  },
  {
    id: "iptv-cat-music",
    name: "IPTV Music",
    type: "iptv",
    url: "https://iptv-org.github.io/iptv/categories/music.m3u",
    enabled: true,
    autoRefresh: false,
    lastSync: 0,
    channelCount: 0,
    builtin: true,
  },
  {
    id: "iptv-cat-news",
    name: "IPTV News",
    type: "iptv",
    url: "https://iptv-org.github.io/iptv/categories/news.m3u",
    enabled: true,
    autoRefresh: false,
    lastSync: 0,
    channelCount: 0,
    builtin: true,
  },
  {
    id: "iptv-cat-comedy",
    name: "IPTV Comedy",
    type: "iptv",
    url: "https://iptv-org.github.io/iptv/categories/comedy.m3u",
    enabled: true,
    autoRefresh: false,
    lastSync: 0,
    channelCount: 0,
    builtin: true,
  },
  {
    id: "iptv-cat-entertainment",
    name: "IPTV Entertainment",
    type: "iptv",
    url: "https://iptv-org.github.io/iptv/categories/entertainment.m3u",
    enabled: true,
    autoRefresh: false,
    lastSync: 0,
    channelCount: 0,
    builtin: true,
  },
  {
    id: "iptv-cat-sports",
    name: "IPTV Sports",
    type: "iptv",
    url: "https://iptv-org.github.io/iptv/categories/sports.m3u",
    enabled: true,
    autoRefresh: false,
    lastSync: 0,
    channelCount: 0,
    builtin: true,
  },
  {
    id: "iptv-org-all",
    name: "IPTV-Org (Global)",
    type: "iptv",
    url: "https://iptv-org.github.io/iptv/index.m3u",
    enabled: false,
    autoRefresh: false,
    lastSync: 0,
    channelCount: 0,
    builtin: true,
  },
  {
    id: "radio-browser",
    name: "Radio Browser (Top)",
    type: "radio",
    url: "https://de1.api.radio-browser.info/json/stations/topclick/500",
    enabled: true,
    autoRefresh: true,
    lastSync: 0,
    channelCount: 0,
    builtin: true,
  },
  {
    id: "radio-israel",
    name: "Radio Israel",
    type: "radio",
    url: "https://de1.api.radio-browser.info/json/stations/bycountry/israel",
    enabled: true,
    autoRefresh: false,
    lastSync: 0,
    channelCount: 0,
    builtin: true,
  },
];
