import type { SearchIntent } from "../webSearch/types";
import type { NewsPanelMode } from "./newsAcceptanceQueries";

/** QA for «חפש חדשות בנושא …» multi-word Hebrew topic queries. */
export type NewsTopicAcceptanceQuery = {
  id: string;
  query: string;
  expectIntents: SearchIntent[];
  expectPanelMode: NewsPanelMode;
  expectEngineQuery: string;
  expectTitleKeywords: string[];
};

export const NEWS_TOPIC_ACCEPTANCE_QUERIES: NewsTopicAcceptanceQuery[] = [
  {
    id: "TOPIC-Q01",
    query: "חפש חדשות בנושא בינה מלאכותית",
    expectIntents: ["news"],
    expectPanelMode: "search",
    expectEngineQuery: "artificial intelligence",
    expectTitleKeywords: ["ai", "artificial", "intelligence", "llm", "openai"],
  },
  {
    id: "TOPIC-Q02",
    query: "חפש חדשות בנושא סייבר ואבטחת מידע",
    expectIntents: ["news"],
    expectPanelMode: "search",
    expectEngineQuery: "cybersecurity",
    expectTitleKeywords: ["cyber", "security", "hack", "breach"],
  },
  {
    id: "TOPIC-Q03",
    query: "חפש חדשות בנושא פוליטיקה בישראל",
    expectIntents: ["news"],
    expectPanelMode: "search",
    expectEngineQuery: "israel politics",
    expectTitleKeywords: ["israel", "netanyahu", "knesset", "gaza", "idf"],
  },
  {
    id: "TOPIC-Q04",
    query: "חפש חדשות בנושא כלכלה ושוק ההון",
    expectIntents: ["news"],
    expectPanelMode: "search",
    expectEngineQuery: "stock market",
    expectTitleKeywords: ["market", "stock", "economy", "nasdaq", "trading"],
  },
  {
    id: "TOPIC-Q05",
    query: "חפש חדשות בנושא טכנולוגיה וסטארטאפים",
    expectIntents: ["news"],
    expectPanelMode: "search",
    expectEngineQuery: "technology startups",
    expectTitleKeywords: ["tech", "startup", "venture", "funding"],
  },
  {
    id: "TOPIC-Q06",
    query: "חפש חדשות בנושא מדע וחלל",
    expectIntents: ["news"],
    expectPanelMode: "search",
    expectEngineQuery: "space science",
    expectTitleKeywords: ["space", "nasa", "science", "research"],
  },
  {
    id: "TOPIC-Q07",
    query: "חפש חדשות בנושא מזג אוויר קיצוני בעולם",
    expectIntents: ["news"],
    expectPanelMode: "search",
    expectEngineQuery: "extreme weather",
    expectTitleKeywords: ["weather", "storm", "climate", "heat", "flood"],
  },
  {
    id: "TOPIC-Q08",
    query: "חפש חדשות בנושא מלחמות וסכסוכים בעולם",
    expectIntents: ["news"],
    expectPanelMode: "search",
    expectEngineQuery: "war conflict",
    expectTitleKeywords: ["war", "conflict", "military", "troops"],
  },
  {
    id: "TOPIC-Q09",
    query: "חפש חדשות בנושא אנרגיה וחשמל ירוק",
    expectIntents: ["news"],
    expectPanelMode: "search",
    expectEngineQuery: "renewable energy",
    expectTitleKeywords: ["energy", "renewable", "solar", "wind", "electric"],
  },
  {
    id: "TOPIC-Q10",
    query: "חפש חדשות בנושא תחבורה ורכב חשמלי",
    expectIntents: ["news"],
    expectPanelMode: "search",
    expectEngineQuery: "electric vehicle",
    expectTitleKeywords: ["electric", "vehicle", "ev", "car", "tesla"],
  },
  {
    id: "TOPIC-Q11",
    query: "חפש חדשות בנושא קריפטו וביטקוין",
    expectIntents: ["news"],
    expectPanelMode: "search",
    expectEngineQuery: "bitcoin crypto",
    expectTitleKeywords: ["bitcoin", "crypto", "ethereum", "blockchain"],
  },
  {
    id: "TOPIC-Q12",
    query: "חפש חדשות בנושא חברות טכנולוגיה גדולות",
    expectIntents: ["news"],
    expectPanelMode: "search",
    expectEngineQuery: "big tech",
    expectTitleKeywords: ["google", "apple", "microsoft", "meta", "amazon", "tech"],
  },
  {
    id: "TOPIC-Q13",
    query: "חפש חדשות בנושא רשתות חברתיות ואינטרנט",
    expectIntents: ["news"],
    expectPanelMode: "search",
    expectEngineQuery: "social media",
    expectTitleKeywords: ["social", "facebook", "meta", "tiktok", "twitter"],
  },
  {
    id: "TOPIC-Q14",
    query: "חפש חדשות בנושא בריאות ורפואה",
    expectIntents: ["news"],
    expectPanelMode: "search",
    expectEngineQuery: "health medicine",
    expectTitleKeywords: ["health", "medical", "medicine", "hospital", "clinical"],
  },
  {
    id: "TOPIC-Q15",
    query: "חפש חדשות בנושא חינוך וטכנולוגיות למידה",
    expectIntents: ["news"],
    expectPanelMode: "search",
    expectEngineQuery: "education technology",
    expectTitleKeywords: ["education", "school", "learning", "university", "edtech"],
  },
  {
    id: "TOPIC-Q16",
    query: "חפש חדשות בנושא חוק ורגולציה טכנולוגית",
    expectIntents: ["news"],
    expectPanelMode: "search",
    expectEngineQuery: "tech regulation",
    expectTitleKeywords: ["regulation", "law", "legal", "antitrust", "compliance"],
  },
  {
    id: "TOPIC-Q17",
    query: "חפש חדשות בנושא צבא וביטחון",
    expectIntents: ["news"],
    expectPanelMode: "search",
    expectEngineQuery: "military defense",
    expectTitleKeywords: ["military", "defense", "army", "idf", "pentagon"],
  },
  {
    id: "TOPIC-Q18",
    query: "חפש חדשות בנושא חלל וחקר היקום",
    expectIntents: ["news"],
    expectPanelMode: "search",
    expectEngineQuery: "space",
    expectTitleKeywords: ["space", "nasa", "rocket", "orbit", "mars"],
  },
  {
    id: "TOPIC-Q19",
    query: "חפש חדשות בנושא גיימינג ותעשיית המשחקים",
    expectIntents: ["news"],
    expectPanelMode: "search",
    expectEngineQuery: "gaming",
    expectTitleKeywords: ["game", "gaming", "playstation", "xbox", "nintendo"],
  },
  {
    id: "TOPIC-Q20",
    query: "חפש חדשות בנושא תרבות ובידור",
    expectIntents: ["news"],
    expectPanelMode: "search",
    expectEngineQuery: "entertainment culture",
    expectTitleKeywords: ["film", "movie", "music", "entertainment", "culture"],
  },
  {
    id: "TOPIC-Q21",
    query: "חפש חדשות בנושא ספורט עולמי",
    expectIntents: ["news"],
    expectPanelMode: "search",
    expectEngineQuery: "sports",
    expectTitleKeywords: ["sport", "football", "soccer", "olympic", "championship"],
  },
  {
    id: "TOPIC-Q22",
    query: "חפש חדשות בנושא אירועים חריגים בעולם",
    expectIntents: ["news"],
    expectPanelMode: "search",
    expectEngineQuery: "breaking news disaster",
    expectTitleKeywords: ["breaking", "disaster", "earthquake", "emergency", "crash"],
  },
  {
    id: "TOPIC-Q23",
    query: "חפש חדשות בנושא חדשנות ובינה מלאכותית יישומית",
    expectIntents: ["news"],
    expectPanelMode: "search",
    expectEngineQuery: "artificial intelligence",
    expectTitleKeywords: ["ai", "innovation", "artificial", "intelligence"],
  },
  {
    id: "TOPIC-Q24",
    query: "חפש חדשות בנושא סטארטאפים ישראליים",
    expectIntents: ["news"],
    expectPanelMode: "search",
    expectEngineQuery: "israel startups",
    expectTitleKeywords: ["startup", "israel", "venture", "funding"],
  },
  {
    id: "TOPIC-Q25",
    query: "חפש חדשות בנושא חקלאות וטכנולוגיות מזון",
    expectIntents: ["news"],
    expectPanelMode: "search",
    expectEngineQuery: "agriculture food tech",
    expectTitleKeywords: ["agriculture", "food", "farm", "crop"],
  },
];
