// @ts-nocheck
import type { CatalogFeed } from "./types";

function peripheryFeed(
  def: Omit<CatalogFeed, "lang" | "region" | "scope" | "tier" | "language" | "sourceType" | "category"> &
    Pick<CatalogFeed, "lang"> &
    Partial<Pick<CatalogFeed, "category" | "fallbackUrls" | "region">>,
): CatalogFeed {
  return {
    language: "multi",
    sourceType: "rss",
    category: "world",
    region: def.region ?? "GLOBAL",
    scope: "global",
    tier: "core",
    ...def,
  };
}

/** RSS from underserved regions — Africa, Asia-Pacific, LatAm, Middle East periphery, etc. */
export const WORLD_PERIPHERY_FEEDS: CatalogFeed[] = [
  // Turkey / Caucasus gateway
  peripheryFeed({
    key: "tr_hurriyet",
    lang: "tr",
    region: "TR",
    url: "https://www.hurriyet.com.tr/rss/gundem",
    label: "Hürriyet",
    tag: "Hürriyet",
    priority: 2,
  }),
  peripheryFeed({
    key: "tr_trtworld",
    lang: "en",
    region: "TR",
    url: "https://news.google.com/rss/search?q=site:trtworld.com&hl=en&gl=TR&ceid=TR:en",
    label: "TRT World",
    tag: "TRT World",
    priority: 3,
  }),
  // South Asia
  peripheryFeed({
    key: "hi_hindu",
    lang: "hi",
    region: "IN",
    url: "https://www.thehindu.com/news/national/?service=rss",
    label: "The Hindu",
    tag: "The Hindu",
    priority: 2,
  }),
  peripheryFeed({
    key: "hi_toi",
    lang: "hi",
    region: "IN",
    url: "https://timesofindia.indiatimes.com/rssfeedstopstories.cms",
    label: "Times of India",
    tag: "TOI",
    priority: 3,
  }),
  peripheryFeed({
    key: "hi_livemint",
    lang: "en",
    region: "IN",
    url: "https://www.livemint.com/rss/news",
    label: "Livemint",
    tag: "Livemint",
    priority: 4,
  }),
  peripheryFeed({
    key: "pk_dawn",
    lang: "en",
    region: "PK",
    url: "https://www.dawn.com/feeds/home",
    label: "Dawn",
    tag: "Dawn",
    priority: 2,
  }),
  peripheryFeed({
    key: "in_dailystar",
    lang: "en",
    region: "BD",
    url: "https://www.thedailystar.net/rss.xml",
    label: "Daily Star",
    tag: "Daily Star",
    priority: 3,
  }),
  // Southeast Asia
  peripheryFeed({
    key: "id_jakpost",
    lang: "en",
    region: "ID",
    url: "https://news.google.com/rss/search?q=site:thejakartapost.com&hl=en&gl=ID&ceid=ID:en",
    label: "Jakarta Post",
    tag: "Jakarta Post",
    priority: 2,
  }),
  peripheryFeed({
    key: "vi_vnnews",
    lang: "vi",
    region: "VN",
    url: "https://vietnamnews.vn/rss/home.rss",
    label: "Vietnam News",
    tag: "Vietnam News",
    priority: 2,
  }),
  peripheryFeed({
    key: "th_bangkokpost",
    lang: "en",
    region: "TH",
    url: "https://www.bangkokpost.com/rss/data/topstories.xml",
    label: "Bangkok Post",
    tag: "Bangkok Post",
    priority: 3,
  }),
  peripheryFeed({
    key: "sg_cna",
    lang: "en",
    region: "SG",
    url: "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml",
    label: "CNA",
    tag: "CNA",
    priority: 2,
  }),
  peripheryFeed({
    key: "sg_straitstimes",
    lang: "en",
    region: "SG",
    url: "https://news.google.com/rss/search?q=site:straitstimes.com&hl=en&gl=SG&ceid=SG:en",
    label: "Straits Times",
    tag: "Straits Times",
    priority: 3,
  }),
  peripheryFeed({
    key: "ph_inquirer",
    lang: "en",
    region: "PH",
    url: "https://news.google.com/rss/search?q=site:inquirer.net&hl=en&gl=PH&ceid=PH:en",
    label: "Inquirer",
    tag: "Inquirer",
    priority: 2,
  }),
  peripheryFeed({
    key: "ph_rappler",
    lang: "en",
    region: "PH",
    url: "https://news.google.com/rss/search?q=site:rappler.com&hl=en&gl=PH&ceid=PH:en",
    label: "Rappler",
    tag: "Rappler",
    priority: 3,
  }),
  // Africa
  peripheryFeed({
    key: "af_allafrica",
    lang: "en",
    region: "AF",
    url: "https://allafrica.com/tools/headlines/rdf/latest/headlines.rdf",
    label: "AllAfrica",
    tag: "AllAfrica",
    priority: 1,
  }),
  peripheryFeed({
    key: "ng_premiumtimes",
    lang: "en",
    region: "NG",
    url: "https://www.premiumtimesng.com/feed",
    label: "Premium Times",
    tag: "Premium Times",
    priority: 2,
  }),
  peripheryFeed({
    key: "gh_ghanaweb",
    lang: "en",
    region: "GH",
    url: "https://news.google.com/rss/search?q=site:ghanaweb.com&hl=en&gl=GH&ceid=GH:en",
    label: "GhanaWeb",
    tag: "GhanaWeb",
    priority: 3,
  }),
  peripheryFeed({
    key: "za_news24",
    lang: "en",
    region: "ZA",
    url: "https://news.google.com/rss/search?q=site:news24.com&hl=en&gl=ZA&ceid=ZA:en",
    label: "News24",
    tag: "News24",
    priority: 2,
  }),
  peripheryFeed({
    key: "za_dailymaverick",
    lang: "en",
    region: "ZA",
    url: "https://news.google.com/rss/search?q=site:dailymaverick.co.za&hl=en&gl=ZA&ceid=ZA:en",
    label: "Daily Maverick",
    tag: "Daily Maverick",
    priority: 3,
  }),
  // Middle East / Gulf (non-blocked)
  peripheryFeed({
    key: "me_mee",
    lang: "en",
    region: "ME",
    url: "https://www.middleeasteye.net/rss",
    label: "Middle East Eye",
    tag: "MEE",
    priority: 2,
  }),
  peripheryFeed({
    key: "ae_national",
    lang: "en",
    region: "AE",
    url: "https://news.google.com/rss/search?q=site:thenationalnews.com&hl=en&gl=AE&ceid=AE:en",
    label: "The National",
    tag: "The National",
    priority: 3,
  }),
  // Francophone Africa / global south (RFI)
  peripheryFeed({
    key: "fr_rfi",
    lang: "fr",
    region: "AF",
    url: "https://www.rfi.fr/en/rss",
    label: "RFI English",
    tag: "RFI",
    priority: 2,
  }),
  // Latin America
  peripheryFeed({
    key: "latam_clarin",
    lang: "es",
    region: "AR",
    url: "https://www.clarin.com/rss/",
    label: "Clarín",
    tag: "Clarín",
    priority: 2,
  }),
  peripheryFeed({
    key: "latam_eltiempo",
    lang: "es",
    region: "CO",
    url: "https://www.eltiempo.com/rss/mundo.xml",
    label: "El Tiempo",
    tag: "El Tiempo",
    priority: 3,
  }),
  peripheryFeed({
    key: "latam_eluniversal",
    lang: "es",
    region: "MX",
    url: "https://news.google.com/rss/search?q=site:eluniversal.com.mx&hl=es&gl=MX&ceid=MX:es",
    label: "El Universal",
    tag: "El Universal",
    priority: 2,
  }),
  peripheryFeed({
    key: "latam_emol",
    lang: "es",
    region: "CL",
    url: "https://news.google.com/rss/search?q=site:emol.com&hl=es&gl=CL&ceid=CL:es",
    label: "Emol",
    tag: "Emol",
    priority: 3,
  }),
  // Taiwan
  peripheryFeed({
    key: "tw_focus",
    lang: "zh",
    region: "TW",
    url: "https://news.google.com/rss/search?q=site:focustaiwan.tw&hl=en&gl=TW&ceid=TW:en",
    label: "Focus Taiwan",
    tag: "Focus Taiwan",
    priority: 2,
  }),
  // Oceania
  peripheryFeed({
    key: "au_abc",
    lang: "en",
    region: "AU",
    url: "https://www.abc.net.au/news/feed/51120/rss.xml",
    label: "ABC Australia",
    tag: "ABC",
    priority: 2,
  }),
  peripheryFeed({
    key: "nz_rnz",
    lang: "en",
    region: "NZ",
    url: "https://www.rnz.co.nz/rss/news.xml",
    label: "RNZ",
    tag: "RNZ",
    priority: 3,
  }),
  // Russia / Iran (alternative voices)
  peripheryFeed({
    key: "ru_meduza",
    lang: "ru",
    region: "RU",
    url: "https://meduza.io/rss/all",
    label: "Meduza",
    tag: "Meduza",
    priority: 3,
  }),
  peripheryFeed({
    key: "ru_mtimes",
    lang: "en",
    region: "RU",
    url: "https://news.google.com/rss/search?q=site:themoscowtimes.com&hl=en&gl=RU&ceid=RU:en",
    label: "Moscow Times",
    tag: "Moscow Times",
    priority: 4,
  }),
  peripheryFeed({
    key: "fa_tehrantimes",
    lang: "fa",
    region: "IR",
    url: "https://www.tehrantimes.com/rss",
    label: "Tehran Times",
    tag: "Tehran Times",
    priority: 3,
  }),
  // Ukraine (additional English voice)
  peripheryFeed({
    key: "uk_kyivpost",
    lang: "en",
    region: "UA",
    url: "https://news.google.com/rss/search?q=site:kyivpost.com&hl=en&gl=UA&ceid=UA:en",
    label: "Kyiv Post",
    tag: "Kyiv Post",
    priority: 3,
  }),
];
