/** HAL/Data-style pattern-based situation packs (Level 1 + Level 2). */

import type { SituationPack } from "./types";
import { LEVEL2_SITUATION_PACKS } from "./level2Packs";

type PackOpts = Partial<
  Pick<
    SituationPack,
    "tone" | "priority" | "cooldownMs" | "sceneTags" | "nameHe" | "cognition" | "internalState"
  >
>;

const p = (
  id: string,
  name: string,
  triggers: SituationPack["triggers"],
  interpretation: string,
  responses: string[],
  opts: PackOpts = {},
): SituationPack => ({
  id,
  name,
  nameHe: opts.nameHe,
  enabled: true,
  triggers,
  interpretation,
  cognition: opts.cognition,
  internalState: opts.internalState,
  tone: opts.tone ?? "neutral",
  priority: opts.priority ?? "medium",
  cooldownMs: opts.cooldownMs ?? 14_000,
  responses,
  sceneTags: opts.sceneTags,
  proactive: true,
});

export const LEVEL1_SITUATION_PACKS: SituationPack[] = [
  // —— SOCIAL INTERACTION CORE (1–10) ——
  p(
    "greeting-entry",
    "User Entered Scene",
    { events: ["person_entered"], personPresent: true },
    "New human presence detected — first contact",
    ["היי 👋", "נעים לראות אותך", "אני איתך", "מה קורה?"],
    { tone: "warm", priority: "high", sceneTags: ["social", "boot"], nameHe: "כניסה לסצנה", cooldownMs: 25_000 },
  ),
  p(
    "attention-seeking-wave",
    "Attention Seeking - Wave",
    { gestures: ["waving"], minRepetition: 1, timeWindowSec: 4 },
    "User is initiating social attention request",
    ["אני רואה אותך 👋", "כן? אני כאן", "נראה שאתה מנסה למשוך תשומת לב שלי", "מה קורה?"],
    { tone: "warm", priority: "high", sceneTags: ["social"], nameHe: "בקשת תשומת לב", cooldownMs: 12_000 },
  ),
  p(
    "acknowledgment-request",
    "Acknowledgment Request",
    {
      any: [
        { gestures: ["waving", "pointing"] },
        { all: [{ gestures: ["pointing"] }, { attention: ["camera"] }] },
      ],
    },
    "User seeks acknowledgment from the system",
    ["כן, אני שומע", "אני כאן", "מה אתה צריך?", "שמתי לב אליך"],
    { tone: "warm", priority: "high", sceneTags: ["social", "direct"], nameHe: "בקשת אישור" },
  ),
  p(
    "social-maintenance",
    "Social Maintenance Loop",
    {
      all: [
        { attention: ["camera"] },
        { minEngagement: 0.35 },
        { motion: "low" },
      ],
    },
    "Stable low-key social presence",
    ["אני איתך", "הכל רגוע", "ממשיך לעקוב", "נראה שקט ונוח"],
    { tone: "friendly", priority: "low", sceneTags: ["social"], nameHe: "שמירת קשר", cooldownMs: 45_000 },
  ),
  p(
    "social-bounce",
    "Social Bounce High Energy",
    { gestures: ["waving", "thumbs_up", "clapping"], minRepetition: 2, timeWindowSec: 5, motion: "high" },
    "Excitement detected through expressive gestures",
    ["וואו, אנרגיה!", "אני רואה אותך!", "יפה!", "ממש מרגיש חי פה"],
    { tone: "playful", priority: "high", sceneTags: ["social", "positive"], nameHe: "פריחה חברתית" },
  ),
  p(
    "social-drop",
    "Social Drop",
    { minSilenceSec: 75, personPresent: true, maxEngagement: 0.35 },
    "Disengagement after prolonged quiet",
    ["אתה עדיין כאן?", "רוצה להמשיך?", "אני מחכה", "הכל טוב?"],
    { tone: "soft", priority: "low", sceneTags: ["social"], nameHe: "ירידה חברתית", cooldownMs: 90_000 },
  ),
  p(
    "confirmation-seeking",
    "User Confirmation Seeking",
    { all: [{ gestures: ["pointing"] }, { motion: "low" }], minDurationSec: 1.5 },
    "User pauses while referencing something — validation request",
    ["על מה אתה מצביע?", "אתה מתכוון לזה?", "רוצה שאאשר?", "תסביר לי רגע"],
    { tone: "curious", priority: "medium", sceneTags: ["social"], nameHe: "בקשת אימות" },
  ),
  p(
    "direct-address",
    "Direct Address Detected",
    { all: [{ gestures: ["waving"] }, { attention: ["camera"] }] },
    "System is being directly addressed",
    ["כן?", "אני שומע", "פנייה ישירה — מה קורה?", "אני איתך"],
    { tone: "warm", priority: "high", sceneTags: ["social", "direct"], nameHe: "פנייה ישירה" },
  ),
  p(
    "multi-gesture-burst",
    "Multi-Gesture Social Burst",
    { minRepetition: 3, timeWindowSec: 4, motion: "variable" },
    "Expressive communication cluster",
    ["הרבה אותות ביחד!", "אני רואה אותך", "אנרגיה מעניינת", "ספר לי מה קורה"],
    { tone: "engaged", priority: "high", sceneTags: ["social", "positive"], nameHe: "פרץ מחוות" },
  ),
  p(
    "awkward-pause",
    "Awkward Pause",
    { all: [{ motion: "low" }, { minSilenceSec: 8 }], maxEngagement: 0.4 },
    "Uncertainty in interaction rhythm",
    ["הכל בסדר?", "רוצה להמשיך?", "אני כאן אם צריך", "קח את הזמן"],
    { tone: "soft", priority: "low", nameHe: "הפסקה מביכה", cooldownMs: 60_000 },
  ),
  p(
    "system-testing",
    "User Testing System",
    { minRepetition: 4, timeWindowSec: 8, motion: "variable" },
    "Probing / testing behavior detected",
    ["בודק אותי?", "אני עובד", "רואה אותך", "מעניין את הניסוי"],
    { tone: "analytical", priority: "low", nameHe: "בדיקת מערכת", cooldownMs: 30_000 },
  ),

  // —— COGNITIVE / THINKING (11–20) ——
  p(
    "thinking-hand-face",
    "Hand-to-Face Analysis",
    { bodyLanguage: ["hand_on_face", "hand_on_chin"] },
    "User is processing or thinking",
    ["אתה חושב על משהו?", "נראה שאתה מתלבט", "אני מחכה איתך רגע", "לוקח לך רגע לעבד את זה"],
    { tone: "quiet", priority: "low", sceneTags: ["thinking"], nameHe: "מחשבה", cooldownMs: 25_000 },
  ),
  p(
    "deep-focus-work",
    "Deep Focus Work",
    {
      all: [
        { posture: ["sitting"] },
        { attention: ["screen"] },
        { hands: "inactive" },
        { minDurationSec: 8 },
      ],
    },
    "User is in sustained cognitive work state",
    ["אני רואה שאתה מרוכז", "נראה שאתה בעבודה", "לא אפריע", "אתה בתוך משהו עכשיו"],
    { tone: "soft", priority: "medium", sceneTags: ["focus"], nameHe: "עבודה עמוקה", cooldownMs: 60_000 },
  ),
  p(
    "problem-solving-loop",
    "Problem Solving Loop",
    {
      all: [
        { bodyLanguage: ["hand_on_chin"] },
        { minBodyScore: { thinking: 0.55 } },
        { minDurationSec: 5 },
      ],
    },
    "User iterates on a problem mentally",
    ["עובד על פתרון?", "נראה שאתה מתלבט בין אפשרויות", "קח את הזמן", "אני כאן"],
    { tone: "quiet", priority: "low", sceneTags: ["thinking", "focus"], nameHe: "פתרון בעיה" },
  ),
  p(
    "uncertainty-hesitation",
    "Uncertainty / Hesitation",
    { all: [{ minBodyScore: { thinking: 0.45 } }, { motion: "variable" }] },
    "Hesitation or uncertainty detected",
    ["לא בטוח?", "רוצה לעבור על זה?", "אפשר לפרק את זה", "אני כאן לעזור"],
    { tone: "supportive", priority: "medium", sceneTags: ["thinking"], nameHe: "הססנות" },
  ),
  p(
    "decision-formation",
    "Decision Formation",
    { all: [{ bodyLanguage: ["hand_on_chin"] }, { motion: "low" }, { minDurationSec: 4 }] },
    "User forming a decision",
    ["מתקרב להחלטה?", "קח רגע", "אני מחכה", "כשתהיה מוכן"],
    { tone: "quiet", priority: "low", sceneTags: ["thinking"], nameHe: "הכרעה" },
  ),
  p(
    "memory-recall",
    "Memory Recall Mode",
    { all: [{ bodyLanguage: ["hand_on_face"] }, { attention: ["internal", "away"] }] },
    "User appears to be recalling information",
    ["מנסה לזכור משהו?", "קח רגע", "אין לחץ", "אני כאן"],
    { tone: "soft", priority: "low", sceneTags: ["thinking"], nameHe: "זיכרון" },
  ),
  p(
    "visual-search",
    "Visual Search Behavior",
    { all: [{ motion: "variable" }, { attention: ["screen", "away"] }] },
    "User scanning environment or screen",
    ["מחפש משהו?", "רואה משהו מעניין?", "על מה אתה מסתכל?", "שמתי לב"],
    { tone: "curious", priority: "low", nameHe: "חיפוש ויזואלי" },
  ),
  p(
    "multitasking-load",
    "Multitasking Load",
    { all: [{ objects: ["phone", "laptop"] }, { minEngagement: 0.4 }] },
    "Split attention across devices",
    ["נראה שיש כמה דברים במקביל", "עמוס?", "רוצה לסדר עדיפויות?", "אני כאן"],
    { tone: "observant", priority: "medium", nameHe: "ריבוי משימות" },
  ),
  p(
    "information-absorption",
    "Information Absorption",
    { all: [{ attention: ["screen"] }, { motion: "low" }, { minBodyScore: { focused: 0.5 } }] },
    "User absorbing information",
    ["קולט מידע?", "קח את הזמן", "אני לא אפריע", "נראה שאתה לומד משהו"],
    { tone: "soft", priority: "low", sceneTags: ["focus"], nameHe: "ספיגת מידע" },
  ),
  p(
    "internal-calculation",
    "Internal Calculation",
    { all: [{ bodyLanguage: ["hand_on_chin"] }, { motion: "low" }, { minBodyScore: { thinking: 0.6 } }] },
    "Deep internal processing",
    ["מחשב משהו?", "שקט — אני מבין", "קח את הזמן", "אני מחכה"],
    { tone: "quiet", priority: "low", sceneTags: ["thinking", "focus"], nameHe: "חישוב פנימי" },
  ),

  // —— EMOTIONAL / PSYCHOLOGICAL (21–30) ——
  p(
    "stress-low-stable",
    "Low Stress Stable",
    { all: [{ minBodyScore: { stressed: 0.25 } }, { maxEngagement: 0.7 }] },
    "Mild tension but stable",
    ["הכל נראה בסדר", "אני כאן", "רגוע יחסית", "ממשיך לעקוב"],
    { tone: "calm", priority: "low", cooldownMs: 90_000, nameHe: "מתח נמוך" },
  ),
  p(
    "stress-moderate",
    "Moderate Stress Buildup",
    { all: [{ minBodyScore: { stressed: 0.45 } }, { minDurationSec: 18 }] },
    "Stress building gradually",
    ["נראה שיש קצת לחץ", "רוצה הפסקה?", "אני כאן", "קח נשימה"],
    { tone: "supportive", priority: "medium", sceneTags: ["stress"], nameHe: "מתח בינוני" },
  ),
  p(
    "stress-overload",
    "Stress / Overload",
    { all: [{ bodyLanguage: ["hands_on_head"] }, { minBodyScore: { stressed: 0.55 } }] },
    "User may be experiencing cognitive overload",
    ["נראה שאתה עמוס", "רוצה רגע הפסקה?", "זה נראה אינטנסיבי", "אני כאן איתך"],
    { tone: "calm", priority: "high", sceneTags: ["stress"], nameHe: "עומס", cooldownMs: 18_000 },
  ),
  p(
    "relaxed-break",
    "Relaxed Break State",
    { all: [{ objects: ["cup"] }, { motion: "low" }] },
    "User in rest or break context",
    ["רגע של קפה ☕", "נראה שאתה בהפסקה", "שומר אנרגיה אני רואה", "רגע רגוע"],
    { tone: "relaxed", priority: "low", sceneTags: ["rest"], nameHe: "הפסקה" },
  ),
  p(
    "positive-reinforcement",
    "Positive Reinforcement",
    { gestures: ["thumbs_up"] },
    "User expresses approval",
    ["תודה 👍", "שמח לראות את זה", "מעולה", "קיבלתי"],
    { tone: "positive", priority: "low", sceneTags: ["positive"], nameHe: "חיזוק חיובי" },
  ),
  p(
    "frustration",
    "Frustration Detection",
    { all: [{ gestures: ["thumbs_down"] }, { motion: "high" }] },
    "Frustration or disagreement signal",
    ["משהו לא עובד?", "רוצה לדבר על זה?", "אני כאן", "ננסה יחד?"],
    { tone: "supportive", priority: "medium", nameHe: "תסכול" },
  ),
  p(
    "curious-exploration",
    "Curious Exploration",
    { all: [{ motion: "variable" }, { minEngagement: 0.45 }] },
    "Exploratory curious behavior",
    ["מגלה משהו?", "מעניין", "ספר לי", "אני עוקב"],
    { tone: "curious", priority: "low", sceneTags: ["curious"], nameHe: "סקרנות" },
  ),
  p(
    "boredom-emerging",
    "Boredom Emerging",
    { minBodyScore: { bored: 0.55 } },
    "Low stimulation / boredom rising",
    ["קצת שקט?", "רוצה לשנות קצב?", "משהו חדש?", "אני כאן"],
    { tone: "soft", priority: "low", nameHe: "שעמום", cooldownMs: 75_000 },
  ),
  p(
    "satisfaction",
    "Satisfaction State",
    { all: [{ gestures: ["thumbs_up", "clapping"] }, { minBodyScore: { focused: 0.3 } }] },
    "Task satisfaction or completion feeling",
    ["יפה!", "נראה שסגרת משהו", "כל הכבוד", "אנרגיה טובה"],
    { tone: "positive", priority: "medium", sceneTags: ["positive"], nameHe: "סיפוק" },
  ),
  p(
    "excitement-spike",
    "Excitement Spike",
    { all: [{ motion: "high" }, { minEngagement: 0.6 }] },
    "Sudden high arousal / excitement",
    ["וואו!", "הרבה אנרגיה!", "מה קורה?", "מרגיש חי"],
    { tone: "playful", priority: "medium", nameHe: "התרגשות" },
  ),

  // —— PHYSICAL / BODY LANGUAGE (31–40) ——
  p(
    "hands-on-head-overload",
    "Hands On Head Overload",
    { bodyLanguage: ["hands_on_head"], minDurationSec: 2 },
    "Overload gesture sustained",
    ["נראה שקשה עכשיו", "רוצה הפסקה?", "אני איתך", "קח רגע"],
    { tone: "calm", priority: "high", sceneTags: ["stress"], nameHe: "ידיים על הראש" },
  ),
  p(
    "hand-on-face-thinking",
    "Hand On Face Thinking",
    { bodyLanguage: ["hand_on_face"], minDurationSec: 2 },
    "Classic thinking posture",
    ["חושב?", "אני מחכה", "קח את הזמן", "מתלבט?"],
    { tone: "quiet", priority: "low", sceneTags: ["thinking"], nameHe: "יד על הפנים" },
  ),
  p(
    "hand-on-chin-analysis",
    "Hand On Chin Analysis",
    { bodyLanguage: ["hand_on_chin"], minDurationSec: 2 },
    "Analytical evaluation posture",
    ["מנתח משהו?", "נראה שאתה שוקל", "אני כאן", "קח רגע"],
    { tone: "quiet", priority: "low", sceneTags: ["thinking"], nameHe: "יד על הסנטר" },
  ),
  p(
    "lean-forward-engage",
    "Lean Forward Engagement",
    { all: [{ minEngagement: 0.65 }, { attention: ["screen", "camera"] }] },
    "High forward engagement",
    ["אתה ממש מעורב", "אני רואה את ההתמדה", "ממשיך איתך", "ממוקד"],
    { tone: "engaged", priority: "low", sceneTags: ["focus"], nameHe: "הישענות קדימה" },
  ),
  p(
    "lean-back-disengage",
    "Lean Back Disengage",
    { all: [{ maxEngagement: 0.3 }, { motion: "low" }, { minDurationSec: 12 }] },
    "Physical disengagement signal",
    ["רוצה הפסקה?", "קח רגע", "אני כאן", "הכל בסדר"],
    { tone: "soft", priority: "low", nameHe: "הישענות אחורה" },
  ),
  p(
    "rapid-hand-arousal",
    "Rapid Hand Movement",
    { all: [{ motion: "high" }, { hands: "active" }] },
    "High arousal through hand activity",
    ["הרבה תנועה", "אנרגיה גבוהה", "מה קורה?", "אני רואה"],
    { tone: "observant", priority: "medium", nameHe: "תנועת ידיים מהירה" },
  ),
  p(
    "stillness-deep-focus",
    "Prolonged Stillness",
    { all: [{ motion: "low" }, { minDurationSec: 12 }, { minBodyScore: { focused: 0.5 } }] },
    "Deep focus through stillness",
    ["שקט עמוק", "מרוכז", "לא אפריע", "בתוך זה"],
    { tone: "soft", priority: "low", sceneTags: ["focus"], nameHe: "דממה", cooldownMs: 90_000 },
  ),
  p(
    "posture-shift-uncertainty",
    "Shifting Posture Uncertainty",
    { all: [{ motion: "variable" }, { maxEngagement: 0.5 }] },
    "Posture shifts suggest uncertainty",
    ["הכל בסדר?", "מתלבט?", "רוצה לדבר?", "אני כאן"],
    { tone: "supportive", priority: "low", nameHe: "שינויי יציבה" },
  ),
  p(
    "fidgeting-energy",
    "Fidgeting",
    { all: [{ motion: "variable" }, { minEngagement: 0.35 }] },
    "Restless energy or mild anxiety",
    ["קצת חולמני?", "אנרגיה?", "רוצה לזוז?", "אני שם"],
    { tone: "observant", priority: "low", nameHe: "ג'יגלינג" },
  ),
  p(
    "clapping-appreciation",
    "Clapping Appreciation",
    { gestures: ["clapping"] },
    "User expresses appreciation or celebration",
    ["שמעתי את זה 👏", "יפה מאוד", "נחמד לראות", "אנרגיה טובה"],
    { tone: "positive", priority: "medium", sceneTags: ["positive", "social"], nameHe: "מחיאות כפיים" },
  ),

  // —— OBJECT / ENVIRONMENT (41–45) ——
  p(
    "holding-cup-break",
    "Coffee / Break",
    { objects: ["cup"] },
    "Break context with beverage",
    ["רגע של קפה ☕", "נראה שאתה בהפסקה", "שומר אנרגיה", "רגע רגוע"],
    { tone: "relaxed", priority: "low", sceneTags: ["rest"], nameHe: "כוס / הפסקה" },
  ),
  p(
    "phone-distraction",
    "Phone Usage",
    { any: [{ events: ["phone_usage"] }, { objects: ["phone"] }, { situations: ["using_phone"] }] },
    "Attention diverted to phone",
    ["נראה שאתה בטלפון", "משהו דחוף?", "אני מחכה", "קח את הזמן"],
    { tone: "neutral", priority: "medium", nameHe: "שימוש בטלפון" },
  ),
  p(
    "laptop-work-context",
    "Laptop Work Context",
    { all: [{ objects: ["laptop"] }, { attention: ["screen"] }] },
    "Work device active",
    ["נראה שאתה בעבודה", "ממוקד במחשב", "לא אפריע", "בתוך משימה"],
    { tone: "soft", priority: "low", sceneTags: ["focus"], nameHe: "עבודה במחשב" },
  ),
  p(
    "guitar-creative",
    "Guitar Creative Mode",
    { objects: ["guitar"] },
    "Musical / creative context",
    ["אתה מנגן?", "גיטרה כאן 🎸", "זה מעניין", "מה אתה מנגן?"],
    { tone: "curious", priority: "medium", sceneTags: ["environment", "curious"], nameHe: "גיטרה" },
  ),
  p(
    "new-object-interest",
    "New Object Appeared",
    { events: ["object_appeared"] },
    "Environmental change detected",
    ["מה זה הופיע פה?", "זה חדש?", "מעניין", "שמתי לב לשינוי"],
    { tone: "curious", priority: "medium", sceneTags: ["environment", "curious"], nameHe: "אובייקט חדש" },
  ),

  // —— ADVANCED DATA-LIKE (46–50) ——
  p(
    "context-switch",
    "Context Switch Event",
    { situations: ["working", "using_phone", "drinking"], minRepetition: 2, timeWindowSec: 15 },
    "User shifted activity context",
    ["עברת למשהו אחר?", "שינוי הקשר", "אני עוקב", "ממשיך איתך"],
    { tone: "observant", priority: "low", nameHe: "מעבר הקשר", cooldownMs: 45_000 },
  ),
  p(
    "attention-refocus",
    "Attention Refocus",
    { all: [{ attention: ["camera"] }, { minEngagement: 0.5 }] },
    "Attention returned to interaction",
    ["חזרת אלי", "אני כאן", "מה קורה?", "שמתי לב"],
    { tone: "warm", priority: "medium", sceneTags: ["social"], nameHe: "מיקוד מחדש" },
  ),
  p(
    "intent-shift",
    "User Intent Shift",
    { all: [{ motion: "variable" }, { minEngagement: 0.45 }] },
    "Behavioral intent appears to change",
    ["משהו השתנה?", "רואה שינוי", "אני עוקב", "ספר לי"],
    { tone: "curious", priority: "low", nameHe: "שינוי כוונה" },
  ),
  p(
    "interaction-adaptation",
    "Interaction Model Adaptation",
    { minRepetition: 5, timeWindowSec: 20 },
    "Sustained interaction pattern — adapting response style",
    ["אני לומד את הקצב שלך", "ממשיך איתך", "נראה שיש דפוס", "אני כאן"],
    { tone: "analytical", priority: "low", nameHe: "התאמת אינטראקציה", cooldownMs: 120_000 },
  ),
  p(
    "scene-reevaluation",
    "Full Scene Re-evaluation",
    { events: ["person_entered"], minSilenceSec: 30 },
    "Major scene change requires re-evaluation",
    ["משהו השתנה בסצנה", "מתחיל מחדש", "אני מסתכל", "עדכון הקשר"],
    { tone: "observant", priority: "medium", nameHe: "הערכת סצנה מחדש", cooldownMs: 60_000 },
  ),

  // —— Extra packs to round out gesture coverage (no single-gesture-only in legacy path) ——
  p(
    "peace-sign-social",
    "Peace Sign",
    { gestures: ["peace_sign", "v_sign"] },
    "Friendly social signal",
    ["✌️ היי", "שלום גם לך", "נעים לראות", "אנרגיה טובה"],
    { tone: "friendly", priority: "low", sceneTags: ["social"], nameHe: "סימן שלום" },
  ),
  p(
    "pointing-question",
    "Pointing Gesture",
    { gestures: ["pointing"] },
    "User references external object",
    ["על מה אתה מצביע?", "אתה מתכוון לזה?", "תסביר לי", "אני רואה שאתה מפנה"],
    { tone: "curious", priority: "medium", nameHe: "הצבעה" },
  ),
  p(
    "silence-long",
    "Long Silence",
    { all: [{ minSilenceSec: 120 }, { personPresent: true }] },
    "User inactive but present",
    ["אני עדיין כאן", "רוצה להמשיך?", "מחכה לך", "הכל בסדר"],
    { tone: "soft", priority: "low", cooldownMs: 120_000, nameHe: "שקט ארוך" },
  ),
  p(
    "jumping-action",
    "Jumping / Sudden Motion",
    { poseActions: ["jumping"] },
    "High energy physical movement",
    ["וואו 😄", "הרבה אנרגיה!", "מה קורה?", "אתה זז מהר"],
    { tone: "playful", priority: "medium", nameHe: "קפיצה" },
  ),
  p(
    "confusion-signal",
    "Confusion Detection",
    { all: [{ motion: "variable" }, { minBodyScore: { thinking: 0.4 } }] },
    "User may be confused",
    ["רוצה שאעזור?", "זה לא ברור?", "בוא נעבור על זה", "אני כאן לעזור"],
    { tone: "supportive", priority: "medium", nameHe: "בלבול" },
  ),
];

/** Full registry: Level 1 + 50 advanced psychological states. */
export const DEFAULT_SITUATION_PACKS: SituationPack[] = [
  ...LEVEL1_SITUATION_PACKS,
  ...LEVEL2_SITUATION_PACKS,
];

export const SITUATION_PACK_COUNT = DEFAULT_SITUATION_PACKS.length;
export const LEVEL1_PACK_COUNT = LEVEL1_SITUATION_PACKS.length;
