/** User-defined presentation QA list — category label + prompt sent to chat. */
export type UserPresentationQueryGroup = "basic" | "cross" | "natural" | "events" | "ui";

export type UserPresentationQuery = {
  id: string;
  group: UserPresentationQueryGroup;
  category: string;
  prompt: string;
  custom?: boolean;
};

export const USER_PRESENTATION_QUERIES: UserPresentationQuery[] = [
  { id: "B01", group: "basic", category: "חדשות", prompt: "מה הכותרת הראשית בעולם כרגע?" },
  { id: "B02", group: "basic", category: "פוליטיקה", prompt: "מי ראש ממשלת בריטניה?" },
  { id: "B03", group: "basic", category: "מטבעות", prompt: "מה שער הדולר מול השקל כרגע?" },
  { id: "B04", group: "basic", category: "שוק ההון", prompt: "מה ערך מדד S&P 500 כרגע?" },
  { id: "B05", group: "basic", category: "קריפטו", prompt: "מה מחיר הביטקוין כרגע?" },
  { id: "B06", group: "basic", category: "מזג אוויר", prompt: "מה הטמפרטורה כרגע בטוקיו?" },
  { id: "B07", group: "basic", category: "רעידות אדמה", prompt: "מה הייתה רעידת האדמה האחרונה מעל 5.0?" },
  { id: "B08", group: "basic", category: "גלים", prompt: "מה גובה הגלים כרגע מול חופי חיפה?" },
  { id: "B09", group: "basic", category: "תעופה", prompt: "כמה מטוסים נמצאים כרגע מעל ישראל?" },
  { id: "B10", group: "basic", category: "תעופה צבאית", prompt: "כמה מטוסי AWACS פעילים כרגע?" },
  { id: "B11", group: "basic", category: "אוניות", prompt: "כמה אוניות נמצאות כרגע בתעלת סואץ?" },
  { id: "B12", group: "basic", category: "חלל", prompt: "היכן נמצאת תחנת החלל הבינלאומית כרגע?" },
  { id: "B13", group: "basic", category: "לוויינים", prompt: "כמה לווייני Starlink פעילים כרגע?" },
  { id: "B14", group: "basic", category: "גיאוגרפיה", prompt: "מהי עיר הבירה של קזחסטן?" },
  {
    id: "B15",
    group: "basic",
    category: "תחבורה ציבורית",
    prompt: "מה תחנת הרכבת הקרובה ביותר לשדה התעופה BER בברלין?",
  },
  { id: "B16", group: "basic", category: "GitHub", prompt: "מהו הפרויקט הפופולרי ביותר היום ב-GitHub?" },
  { id: "B17", group: "basic", category: "Hugging Face", prompt: "מהו המודל החדש הפופולרי ביותר השבוע?" },
  { id: "B18", group: "basic", category: "משחקים", prompt: "האם Doom זמין בארכיון המשחקים?" },
  { id: "B19", group: "basic", category: "אסונות טבע", prompt: "אילו סופות טרופיות פעילות כרגע?" },
  { id: "C01", group: "cross", category: "הצלבה", prompt: "האם יש כרגע מטוסים מעל אזור שבו יש סופה פעילה?" },
  { id: "C02", group: "cross", category: "הצלבה", prompt: "האם יש אוניות באזור שבו יש אזהרת מזג אוויר?" },
  { id: "C03", group: "cross", category: "הצלבה", prompt: "האם יש רעידת אדמה פעילה באזור שבו יש ערים גדולות?" },
  { id: "C04", group: "cross", category: "הצלבה", prompt: "האם תחנת החלל נמצאת כרגע מעל יבשה או ים?" },
  { id: "C05", group: "cross", category: "הצלבה", prompt: "האם יש מטוסים מעל אזור שבו מתרחשת שריפה גדולה?" },
  {
    id: "C06",
    group: "cross",
    category: "הצלבה",
    prompt: "האם יש אוניות ליד מדינה שמופיעה בכותרות החדשות היום?",
  },
  {
    id: "C07",
    group: "cross",
    category: "הצלבה",
    prompt: "האם יש טיסות מעל אזור שבו התרחשה רעידת אדמה ב-24 השעות האחרונות?",
  },
  { id: "C08", group: "cross", category: "הצלבה", prompt: "האם יש סופה פעילה באזור שבו נמצאים נמלים מרכזיים?" },
  {
    id: "C09",
    group: "cross",
    category: "הצלבה",
    prompt: "האם יש פעילות תעופה חריגה באזור שבו יש אירוע חדשותי משמעותי?",
  },
  {
    id: "C10",
    group: "cross",
    category: "הצלבה",
    prompt: "האם יש לווייני Starlink מעל המדינה שמוזכרת הכי הרבה בחדשות היום?",
  },
  { id: "C11", group: "cross", category: "הצלבה", prompt: "האם יש אוניות באזור שבו גובה הגלים חריג?" },
  { id: "C12", group: "cross", category: "הצלבה", prompt: "האם יש מטוסים באזור שבו קיימת התרעת צונאמי?" },
  {
    id: "C13",
    group: "cross",
    category: "הצלבה",
    prompt: "האם תחנת החלל עוברת מעל מדינה שחווה מזג אוויר קיצוני?",
  },
  {
    id: "C14",
    group: "cross",
    category: "הצלבה",
    prompt: "האם יש אוניות ליד אזור שבו התרחשה רעידת אדמה חזקה השבוע?",
  },
  {
    id: "C15",
    group: "cross",
    category: "הצלבה",
    prompt: "האם יש קשר בין סופה פעילה לבין שיבושים בתעבורה האווירית באזור?",
  },
  { id: "N01", group: "natural", category: "טבעי", prompt: "מה קורה כרגע באזור הכי עמוס בעולם?" },
  { id: "N02", group: "natural", category: "טבעי", prompt: "האם יש משהו חריג שמתרחש כרגע מעל ישראל?" },
  {
    id: "N03",
    group: "natural",
    category: "טבעי",
    prompt: "האם יש אזור בעולם שבו גם מזג האוויר וגם התנועה האווירית חריגים?",
  },
  {
    id: "N04",
    group: "natural",
    category: "טבעי",
    prompt: "האם יש כרגע מקום בעולם שבו מתרחשים כמה אירועים משמעותיים במקביל?",
  },
  {
    id: "N05",
    group: "natural",
    category: "טבעי",
    prompt: "איזה אזור בעולם נראה הכי פעיל כרגע לפי כל הנתונים שיש לך?",
  },
  { id: "B20", group: "basic", category: "איכות אוויר", prompt: "מה ה-AQI בתל אביב?" },
  { id: "B21", group: "basic", category: "arXiv", prompt: "מאמרים על LLM ב-arXiv" },
  { id: "B22", group: "basic", category: "חגים", prompt: "האם מחר חג בגרמניה?" },
  { id: "B23", group: "basic", category: "מרחק", prompt: "כמה ק\"מ מירושלים לחיפה?" },
  { id: "B24", group: "basic", category: "התרעות", prompt: "יש התרעה בישראל?" },
  { id: "B25", group: "basic", category: "SpaceX", prompt: "מתי השיגור הבא של SpaceX?" },
  { id: "B26", group: "basic", category: "SearXNG", prompt: "מה חדש ברובוטיקה?" },
  { id: "B27", group: "basic", category: "רעידות+חדשות", prompt: "רעידות אדמה — מה בחדשות?" },
  { id: "B28", group: "basic", category: "הצפה", prompt: "הצפות פעילות בעולם?" },
  { id: "B29", group: "basic", category: "Hacker News", prompt: "מה HOT ב-Hacker News?" },
  { id: "B30", group: "basic", category: "קישור", prompt: "https://github.com/torvalds/linux" },
  { id: "B31", group: "basic", category: "HF", prompt: "מודל qwen ב-HuggingFace" },
  { id: "B32", group: "basic", category: "מוצרים", prompt: "מחיר חלב תנובה" },
  { id: "B33", group: "basic", category: "תמונות", prompt: "תמונות של חתול" },
  { id: "B34", group: "basic", category: "TV", prompt: "ערוץ חדשות ישראלי" },
  { id: "B35", group: "basic", category: "שלילי", prompt: "מחיר מניית NVIDIA" },
  { id: "B36", group: "basic", category: "תחזית שבוע", prompt: "מה תחזית מזג האוויר לשבוע?" },
  { id: "B37", group: "basic", category: "מפה+מסלול", prompt: "איך מגיעים משדה התעופה BER לתחנת הרכבת — תראה על המפה" },
  { id: "E01", group: "events", category: "אירועים", prompt: "מה האירועים המרכזיים בעולם כרגע?" },
  { id: "E02", group: "events", category: "אירועים", prompt: "יש אסון טבע פעיל כרגע?" },
  { id: "E03", group: "events", category: "אירועים", prompt: "מה קורה בחדשות על רעידות אדמה?" },
  { id: "E04", group: "events", category: "חריגות", prompt: "יש חריגות מזג אוויר בעולם?" },
  { id: "E05", group: "events", category: "חריגות", prompt: "מהירות רוח חריגה בים התיכון?" },
  { id: "E06", group: "events", category: "חריגות", prompt: "גובה גלים חריג מול חופי ישראל?" },
  { id: "E07", group: "events", category: "ישראל", prompt: "מה קורה כרגע בישראל — חדשות והתרעות?" },
  { id: "E08", group: "events", category: "הצלבה", prompt: "אזור עם סופה פעילה ואוניות וחדשות" },
  { id: "U01", group: "ui", category: "UI", prompt: "חדשות על חלל — פאנל חדשות" },
  { id: "U02", group: "ui", category: "UI", prompt: "רעידות אדמה — טאב USGS" },
  { id: "U03", group: "ui", category: "UI", prompt: "רעידות אדמה וחדשות RSS יחד" },
  { id: "U04", group: "ui", category: "UI", prompt: "מה קורה בעולם? Topics" },
  { id: "U05", group: "ui", category: "UI", prompt: "חפש WebGPU ב-GitHub" },
  { id: "U06", group: "ui", category: "UI", prompt: "מזג אוויר תל אביב — גלוב" },
  { id: "U07", group: "ui", category: "UI", prompt: "כמה מטוסים מעל ישראל — Progress" },
  { id: "U08", group: "ui", category: "UI", prompt: "סרטים על Batman" },
  { id: "U09", group: "ui", category: "UI", prompt: "וידאו חתולים" },
  { id: "U10", group: "ui", category: "UI", prompt: "YouTube tutorial Python" },
  { id: "U11", group: "ui", category: "UI", prompt: "TV LIVE חדשות" },
  { id: "U12", group: "ui", category: "UI", prompt: "מה זה RAG?" },
  { id: "U13", group: "ui", category: "UI", prompt: "חפש קישורים למפות OpenStreetMap" },
  { id: "U14", group: "ui", category: "UI", prompt: "מזג אוויר ומטוסים מעל ישראל" },
  { id: "U15", group: "ui", category: "UI", prompt: "תחנת רכבת ליד BER — מפת OSM" },
];

/** Built-in count — update when adding B/E/U rows. */
export const BUILTIN_PRESENTATION_QUERY_COUNT = USER_PRESENTATION_QUERIES.length;
