import type { NewsPanelMode } from "../groveeNews/newsAcceptanceQueries";
import type { AnswerShape, SearchIntent } from "./types";
import type { SearchRouting } from "./resolveSearchHandoff";

/**
 * AI chat → search handoff scenarios.
 * Maps natural-language user requests to minimal search terms + routing.
 *
 * Run: npm test -- app/src/webSearch/aiSearchRoutingQa.test.ts
 * Manual: app/src/webSearch/AI_SEARCH_SCENARIOS.md
 */
export type AiSearchScenario = {
  id: string;
  category: string;
  userQuery: string;
  expectIntents: SearchIntent[];
  expectSearchTerms: string[];
  expectRouting: SearchRouting;
  expectPanelMode?: NewsPanelMode;
  /** Default true — static facts / casual phrasing may skip needsWebSearch gate. */
  expectNeedsWebSearch?: boolean;
  answerShape?: AnswerShape;
  blendNewsWithWeb?: boolean;
  verifyHe: string;
};

export const AI_SEARCH_SCENARIOS: AiSearchScenario[] = [
  {
    id: "AI-N01",
    category: "חדשות · סקירה",
    userQuery: "מה קורה בעולם?",
    expectIntents: ["news"],
    expectSearchTerms: ["world"],
    expectRouting: "regex",
    expectPanelMode: "topics",
    answerShape: "overview",
    blendNewsWithWeb: true,
    verifyHe: "פאנל Topics · מגוון נושאים · grovee-news ok",
  },
  {
    id: "AI-N02",
    category: "חדשות · סקירה",
    userQuery: "תן לי סקירה של מה שקורה היום בעולם",
    expectIntents: ["hackernews", "github"],
    expectSearchTerms: ["technology"],
    expectRouting: "regex",
    answerShape: "overview",
    blendNewsWithWeb: true,
    verifyHe: "timely overview · HN+GitHub+RSS blend",
  },
  {
    id: "AI-N03",
    category: "חדשות · סקירה",
    userQuery: "מה הכותרות המובילות בעולם עכשיו?",
    expectIntents: ["news"],
    expectSearchTerms: ["world"],
    expectRouting: "regex",
    expectPanelMode: "topics",
    verifyHe: "Topics digest · BBC/CNN/Guardian",
  },
  {
    id: "AI-N04",
    category: "חדשות · סקירה",
    userQuery: "מה קורה בישראל?",
    expectIntents: ["news"],
    expectSearchTerms: ["israel"],
    expectRouting: "regex",
    expectPanelMode: "topics",
    verifyHe: "Topics עם נדבך ישראלי",
  },
  {
    id: "AI-N05",
    category: "חדשות · סקירה",
    userQuery: "ספר לי חדשות היום בבקשה",
    expectIntents: ["news"],
    expectSearchTerms: ["חדשות"],
    expectRouting: "regex",
    expectPanelMode: "topics",
    verifyHe: "דיגסט יומי · grovee-news",
  },
  {
    id: "AI-N10",
    category: "חדשות · ניסוח מורכב",
    userQuery: "חפש חדשות על איראן וגרעין",
    expectIntents: ["news"],
    expectSearchTerms: ["iran"],
    expectRouting: "regex",
    expectPanelMode: "search",
    blendNewsWithWeb: true,
    verifyHe: "Search · iran/nuclear",
  },
  {
    id: "AI-N11",
    category: "חדשות · ניסוח מורכב",
    userQuery: "חפש חדשות על טסלה",
    expectIntents: ["news"],
    expectSearchTerms: ["טסלה"],
    expectRouting: "regex",
    expectPanelMode: "search",
    blendNewsWithWeb: true,
    verifyHe: "Search · Tesla headlines",
  },
  {
    id: "AI-N12",
    category: "חדשות · ניסוח מורכב",
    userQuery: "חדשות על OpenAI",
    expectIntents: ["news"],
    expectSearchTerms: ["openai"],
    expectRouting: "regex",
    expectPanelMode: "search",
    verifyHe: "Search · OpenAI",
  },
  {
    id: "AI-N13",
    category: "חדשות · ניסוח מורכב",
    userQuery: "חדשות על אוקראינה",
    expectIntents: ["news"],
    expectSearchTerms: ["ukraine"],
    expectRouting: "regex",
    expectPanelMode: "search",
    verifyHe: "Search · Ukraine",
  },
  {
    id: "AI-N14",
    category: "חדשות · ניסוח מורכב",
    userQuery: "חדשות על המצב בעזה",
    expectIntents: ["news"],
    expectSearchTerms: ["gaza"],
    expectRouting: "regex",
    expectPanelMode: "search",
    verifyHe: "Search · Gaza",
  },
  {
    id: "AI-N15",
    category: "חדשות · ניסוח מורכב",
    userQuery: "חפש לי חדשות על מה שקורה בלונדון",
    expectIntents: ["news"],
    expectSearchTerms: ["london"],
    expectRouting: "regex",
    expectPanelMode: "search",
    blendNewsWithWeb: true,
    verifyHe: "Search · london",
  },
  {
    id: "AI-N20",
    category: "חדשות · נושא מפורש",
    userQuery: "חפש חדשות בנושא בינה מלאכותית",
    expectIntents: ["news"],
    expectSearchTerms: ["artificial intelligence"],
    expectRouting: "regex",
    expectPanelMode: "search",
    blendNewsWithWeb: true,
    verifyHe: "AI/LLM headlines",
  },
  {
    id: "AI-N21",
    category: "חדשות · נושא מפורש",
    userQuery: "חפש חדשות על חלל",
    expectIntents: ["news"],
    expectSearchTerms: ["space"],
    expectRouting: "regex",
    expectPanelMode: "search",
    blendNewsWithWeb: true,
    verifyHe: "space/nasa",
  },
  {
    id: "AI-N23",
    category: "חדשות · נושא מפורש",
    userQuery: "latest news about Ukraine",
    expectIntents: ["news"],
    expectSearchTerms: ["ukraine"],
    expectRouting: "regex",
    expectPanelMode: "search",
    blendNewsWithWeb: true,
    verifyHe: "English Search",
  },
  {
    id: "AI-T01",
    category: "נושא טכנולוגי",
    userQuery: "מה קורה בעולם הרובוטיקה?",
    expectIntents: ["arxiv", "github", "hackernews", "news"],
    expectSearchTerms: ["robotics"],
    expectRouting: "regex",
    blendNewsWithWeb: true,
    verifyHe: "HN+GitHub+arXiv+RSS",
  },
  {
    id: "AI-T02",
    category: "נושא טכנולוגי",
    userQuery: "מה חדש בעולם הגיימינג?",
    expectIntents: ["github", "hackernews", "news"],
    expectSearchTerms: ["gaming"],
    expectRouting: "regex",
    blendNewsWithWeb: true,
    verifyHe: "gaming multi-source",
  },
  {
    id: "AI-T03",
    category: "נושא טכנולוגי",
    userQuery: "מה חדש בתחום הבינה המלאכותית?",
    expectIntents: ["github", "hackernews", "huggingface"],
    expectSearchTerms: ["artificial intelligence"],
    expectRouting: "regex",
    verifyHe: "HN+GitHub+HF",
  },
  {
    id: "AI-T04",
    category: "נושא טכנולוגי",
    userQuery: "מה מחיר הביטקוין ומה חדש בקריפטו?",
    expectIntents: ["crypto"],
    expectSearchTerms: ["ביטקוין"],
    expectRouting: "regex",
    verifyHe: "CoinGecko",
  },
  {
    id: "AI-T05",
    category: "נושא טכנולוגי",
    userQuery: "חפש חדשות על כלכלה",
    expectIntents: ["news"],
    expectSearchTerms: ["economy"],
    expectRouting: "regex",
    expectPanelMode: "search",
    blendNewsWithWeb: true,
    verifyHe: "economy blend",
  },
  {
    id: "AI-W01",
    category: "מזג אוויר",
    userQuery: "קר בחוץ, מה הטמפרטורה בתל אביב?",
    expectIntents: ["weather"],
    expectSearchTerms: ["תל אביב"],
    expectRouting: "regex",
    verifyHe: "Open-Meteo",
  },
  {
    id: "AI-W02",
    category: "מזג אוויר",
    userQuery: "האם צפוי גשם בלונדון מחר?",
    expectIntents: ["weather"],
    expectSearchTerms: ["לונדון"],
    expectRouting: "regex",
    verifyHe: "London forecast",
  },
  {
    id: "AI-W03",
    category: "מזג אוויר",
    userQuery: "מה מזג האוויר בתל אביב",
    expectIntents: ["weather"],
    expectSearchTerms: ["תל אביב"],
    expectRouting: "regex",
    verifyHe: "regex fast path",
  },
  {
    id: "AI-M01",
    category: "ים",
    userQuery: "גובה גלים בתל אביב היום",
    expectIntents: ["marine"],
    expectSearchTerms: ["תל אביב"],
    expectRouting: "regex",
    verifyHe: "Marine API",
  },
  {
    id: "AI-A01",
    category: "תעופה",
    userQuery: "כמה מטוסים נמצאים כרגע מעל ישראל?",
    expectIntents: ["aviation"],
    expectSearchTerms: ["ישראל"],
    expectRouting: "regex",
    answerShape: "count",
    verifyHe: "ADSB",
  },
  {
    id: "AI-A02",
    category: "תעופה",
    userQuery: "מה העומס בשמי ישראל?",
    expectIntents: ["aviation"],
    expectSearchTerms: ["ישראל"],
    expectRouting: "regex",
    verifyHe: "aviation routing",
  },
  {
    id: "AI-S01",
    category: "חלל",
    userQuery: "איפה תחנת החלל הבינלאומית עכשיו?",
    expectIntents: ["satellite"],
    expectSearchTerms: ["תחנת החלל"],
    expectRouting: "regex",
    verifyHe: "ISS",
  },
  {
    id: "AI-E01",
    category: "רעידות אדמה",
    userQuery: "היו רעידות אדמה חזקות הלילה?",
    expectIntents: ["earthquake"],
    expectSearchTerms: ["רעידות"],
    expectRouting: "regex",
    verifyHe: "USGS",
  },
  {
    id: "AI-X01",
    category: "מקורות מרובים",
    userQuery: "מה מזג האוויר וכמה מטוסים מעל ישראל?",
    expectIntents: ["weather", "aviation"],
    expectSearchTerms: ["ישראל"],
    expectRouting: "regex",
    verifyHe: "weather+aviation",
  },
  {
    id: "AI-X02",
    category: "מקורות מרובים",
    userQuery: "האם יש סופה פעילה באירופה?",
    expectIntents: ["disaster", "weather"],
    expectSearchTerms: ["אירופה"],
    expectRouting: "regex",
    verifyHe: "GDACS+weather",
  },
  {
    id: "AI-G01",
    category: "GitHub",
    userQuery: "חפש פרויקטים בנושא face recognition",
    expectIntents: ["github"],
    expectSearchTerms: ["face"],
    expectRouting: "regex",
    verifyHe: "GitHub repos",
  },
  {
    id: "AI-G02",
    category: "GitHub",
    userQuery: "חפש פרויקטים בנושא WebGPU",
    expectIntents: ["github"],
    expectSearchTerms: ["webgpu"],
    expectRouting: "regex",
    verifyHe: "GitHub stars",
  },
  {
    id: "AI-H01",
    category: "Hugging Face",
    userQuery: "gemma models huggingface",
    expectIntents: ["huggingface"],
    expectSearchTerms: ["gemma"],
    expectRouting: "regex",
    expectNeedsWebSearch: false,
    verifyHe: "HF models · topical regex",
  },
  {
    id: "AI-R01",
    category: "arXiv",
    userQuery: "transformer papers arxiv",
    expectIntents: ["arxiv"],
    expectSearchTerms: ["transformer"],
    expectRouting: "regex",
    verifyHe: "arXiv",
  },
  {
    id: "AI-K01",
    category: "Wikipedia",
    userQuery: "חפש מידע על Albert Einstein",
    expectIntents: ["news", "hackernews", "github"],
    expectSearchTerms: ["Einstein"],
    expectRouting: "regex",
    verifyHe: "חיפוש מפורש → blend; Wikipedia דרך Gemma אם אין RSS",
  },
  {
    id: "AI-F01",
    category: "מטבעות",
    userQuery: "כמה שקלים שווים 100 דולר?",
    expectIntents: ["currency"],
    expectSearchTerms: ["100"],
    expectRouting: "regex",
    verifyHe: "Frankfurter",
  },
  {
    id: "AI-F02",
    category: "מדינות",
    userQuery: "מה הבירה של גרמניה?",
    expectIntents: ["country"],
    expectSearchTerms: ["גרמניה"],
    expectRouting: "regex",
    expectNeedsWebSearch: false,
    verifyHe: "REST Countries · static",
  },
  {
    id: "AI-F03",
    category: "זמן",
    userQuery: "מה השעה בניו יורק?",
    expectIntents: ["worldtime"],
    expectSearchTerms: ["ניו יורק"],
    expectRouting: "regex",
    verifyHe: "WorldTime",
  },
  {
    id: "AI-F04",
    category: "קריפטו",
    userQuery: "מה מחיר הביטקוין עכשיו?",
    expectIntents: ["crypto"],
    expectSearchTerms: ["ביטקוין"],
    expectRouting: "regex",
    verifyHe: "CoinGecko",
  },
  {
    id: "AI-P01",
    category: "Planner fallback",
    userQuery: "מה המגמות החמות בטכנולוגיה השנה?",
    expectIntents: ["hackernews", "github"],
    expectSearchTerms: ["technology"],
    expectRouting: "regex",
    verifyHe: "topical HN+GitHub",
  },
  {
    id: "AI-L01",
    category: "קישור",
    userQuery: "https://github.com/Theicd/GROVEEMODEL",
    expectIntents: ["link"],
    expectSearchTerms: ["github.com"],
    expectRouting: "regex",
    verifyHe: "URL context",
  },
];

export type AiSearchGapScenario = {
  id: string;
  userQuery: string;
  workingQuery: string;
  expectSearchTerms: string[];
  verifyHe: string;
};

export const AI_SEARCH_GAP_SCENARIOS: AiSearchGapScenario[] = [
  {
    id: "GAP-N01",
    userQuery: "שמעתי משהו על איראן וגרעין, מה קורה שם?",
    workingQuery: "חפש חדשות על איראן וגרעין",
    expectSearchTerms: ["iran"],
    verifyHe: "בלי «חדשות» אין חיפוש — planner צריך iran",
  },
  {
    id: "GAP-N02",
    userQuery: "יש משהו חדש עם טסלה והמניה שלה?",
    workingQuery: "חפש חדשות על טסלה",
    expectSearchTerms: ["טסלה"],
    verifyHe: "ניסוח שיחה · חלופה AI-N11",
  },
  {
    id: "GAP-N03",
    userQuery: "מה השמועות על OpenAI לאחרונה?",
    workingQuery: "מה החדשות האחרונות על OpenAI?",
    expectSearchTerms: ["openai"],
    verifyHe: "«שמועות» לא מפעיל news",
  },
  {
    id: "GAP-N04",
    userQuery: "מה המצב הביטחוני בעזה?",
    workingQuery: "חדשות על עזה",
    expectSearchTerms: ["gaza"],
    verifyHe: "planner צריך gaza",
  },
  {
    id: "GAP-P01",
    userQuery: "ספר לי על המצב הכלכלי בעולם בצורה כללית",
    workingQuery: "חפש חדשות על כלכלה",
    expectSearchTerms: ["economy"],
    verifyHe: "שיחה כללית · חלופה AI-T05",
  },
];

export const COMPACT_PLANNER_SCHEMA_HE = `המודל מחזיר רק JSON (ללא הסבר):
{"queries":["מונח חיפוש אחד"],"answerShape":"short_fact|bullet_list|overview|count","useWebFallback":false}
כללים: מקסימום שאילתה אחת · intents נקבעים בקוד · useWebFallback רק כשאין API מובנה`;
